#  Copyright (c) 2022 Jakub Vesely
#  This software is published under MIT license. Full text of the license is available at https://opensource.org/licenses/MIT

class SpecialKeys:
  left = "left"
  right = "right"
  up = "up"
  down = "down"
  space = "space"
  delete = "delete"
  backspace = "backspace"
  enter = "enter"
  page_up = "page up"
  page_down = "page down"
  home = "home"
  end = "end"
  ctrl = "ctrl"
  right_ctrl = "right ctrl"
  alt = "alt"
  right_alt = "right alt"
  window = "left windows"
  menu = "menu"
  caps_lock = "caps lock"
  tab = "tab"
  shift = "shift"
  right_shift = "right_shift"
  insert = "insert"
  pause = "pause"
  ok = "ok"
