include("$(PORT_DIR)/boards/manifest.py")
c_module("$(BOARD_DIR)/zigbee")
freeze("$(PORT_DIR)/boards/HUGO/modules")
freeze("$(PORT_DIR)/boards/HUGO/externals", "ssd1306.py", True)
freeze("$(PORT_DIR)/boards/HUGO/externals", "vl53l1x.py", True)
freeze("$(PORT_DIR)/boards/HUGO/externals/mpu9250", "ak8963.py", True)
freeze("$(PORT_DIR)/boards/HUGO/externals/mpu9250", "mpu6500.py", True)
freeze("$(PORT_DIR)/boards/HUGO/externals/mpu9250", "mpu9250.py", True)
freeze("$(PORT_DIR)/boards/HUGO/externals/BME280", "bme280_float.py", True)
